services:
  - type: web
    name: jose-sastre-email-service
    env: python
    buildCommand: ""
    startCommand: "python server.py"
    plan: free
    region: frankfurt
    autoDeploy: true
    envVars: []